//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADT_ModelContainer1 : DbContext
    {
        public ADT_ModelContainer1()
            : base("name=ADT_ModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADTMessage> ADTMessages { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
    }
}
