//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTEntityFramework
{
    using System.Data.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class ADTMessage
    {
        public ADTMessage(){} // Here is the zero-parameter constructor
    
        public ADTMessage( // Here is the initialization constructor
            string _MessageID,
            string _MessageType,
            string _PreviousLocationID,
            string _LocationID,
            string _PreviousStatus,
            string _Status,
            string _KickedPatientID,
            System.DateTime _GeneratedTimestamp,
            System.DateTime _MessageTimestamp,
            string _PatientID )
        {
            MessageID = _MessageID;
            MessageType = _MessageType;
            PreviousLocationID = _PreviousLocationID;
            LocationID = _LocationID;
            PreviousStatus = _PreviousStatus;
            Status = _Status;
            KickedPatientID = _KickedPatientID;
            GeneratedTimestamp = _GeneratedTimestamp;
            MessageTimestamp = _MessageTimestamp;
            PatientID = _PatientID;
    
        }
    
        public string MessageID { get; set; }
        public string MessageType { get; set; }
        public string PreviousLocationID { get; set; }
        public string LocationID { get; set; }
        public string PreviousStatus { get; set; }
        public string Status { get; set; }
        public string KickedPatientID { get; set; }
        public System.DateTime GeneratedTimestamp { get; set; }
        public System.DateTime MessageTimestamp { get; set; }
        public string PatientID { get; set; }
    
        public void CreateInDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.ADTMessages.Attach(this);
                db.ADTMessages.Add(this);
                db.SaveChanges();
            }
        }
    
        public void UpdateInDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.ADTMessages.Attach(this);
                db.Entry(this).State = EntityState.Modified;
                db.SaveChanges();
            }
        }
    
        public void RemoveFromDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.ADTMessages.Attach(this);
                db.ADTMessages.Remove(this);
                db.SaveChanges();
            }
        }
    
    }
}
