//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTEntityFramework
{
    using System.Data.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location(){} // Here is the zero-parameter constructor
    
        public Location( // Here is the initialization constructor
            string _LocationID )
        {
            LocationID = _LocationID;
    
        }
    
        public string LocationID { get; set; }
    
        public void CreateInDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.Locations.Attach(this);
                db.Locations.Add(this);
                db.SaveChanges();
            }
        }
    
        public void UpdateInDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.Locations.Attach(this);
                db.Entry(this).State = EntityState.Modified;
                db.SaveChanges();
            }
        }
    
        public void RemoveFromDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.Locations.Attach(this);
                db.Locations.Remove(this);
                db.SaveChanges();
            }
        }
    
    }
}
