//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTEntityFramework
{
    using System.Data.Entity;
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient(){} // Here is the zero-parameter constructor
    
        public Patient( // Here is the initialization constructor
            string _PatientID,
            string _FirstName,
            string _LastName,
            string _Status,
            string _LocationID )
        {
            PatientID = _PatientID;
            FirstName = _FirstName;
            LastName = _LastName;
            Status = _Status;
            LocationID = _LocationID;
    
        }
    
        public string PatientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Status { get; set; }
        public string LocationID { get; set; }
    
        public void CreateInDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.Patients.Attach(this);
                db.Patients.Add(this);
                db.SaveChanges();
            }
        }
    
        public void UpdateInDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.Patients.Attach(this);
                db.Entry(this).State = EntityState.Modified;
                db.SaveChanges();
            }
        }
    
        public void RemoveFromDatabase()
        {
            using (var db = new ADT_ModelContainer1())
            {
                db.Patients.Attach(this);
                db.Patients.Remove(this);
                db.SaveChanges();
            }
        }
    
    }
}
